# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 07:47
from __future__ import unicode_literals

import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('name', models.CharField(max_length=512, verbose_name='company')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('description', models.TextField(default='', verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'verbose_name': 'company',
            },
        ),
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'data items',
                'verbose_name': 'data item',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('dataitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='nc_core.DataItem')),
                ('data', models.CharField(max_length=30, verbose_name='post_address')),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'verbose_name': 'address',
            },
            bases=('nc_core.dataitem',),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('dataitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='nc_core.DataItem')),
                ('data', models.EmailField(max_length=30, verbose_name='mail')),
            ],
            options={
                'verbose_name_plural': 'mails',
                'verbose_name': 'mail',
            },
            bases=('nc_core.dataitem',),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('dataitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='nc_core.DataItem')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=25, verbose_name='phone')),
                ('data', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
            ],
            options={
                'verbose_name_plural': 'phones',
                'verbose_name': 'phone',
            },
            bases=('nc_core.dataitem',),
        ),
        migrations.CreateModel(
            name='Skype',
            fields=[
                ('dataitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='nc_core.DataItem')),
                ('data', models.CharField(max_length=30, verbose_name='login')),
            ],
            options={
                'verbose_name_plural': 'skype',
                'verbose_name': 'skype',
            },
            bases=('nc_core.dataitem',),
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('dataitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='nc_core.DataItem')),
                ('data', models.CharField(max_length=30, verbose_name='url')),
            ],
            options={
                'verbose_name_plural': 'websites',
                'verbose_name': 'website',
            },
            bases=('nc_core.dataitem',),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_nc_core.dataitem_set+', to='contenttypes.ContentType'),
        ),
    ]
