# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 07:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nc_workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nc_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_board',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nc_workflow.Board', verbose_name='default board'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
