# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nc_core', '0002_auto_20180221_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
