# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 07:47
from __future__ import unicode_literals

import django.utils.timezone
import easy_thumbnails.fields
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import nc_auth.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=512, verbose_name='first name')),
                ('last_name', models.CharField(max_length=512, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=512, verbose_name='middle name')),
                ('notes', models.CharField(blank=True, default='', max_length=1024, verbose_name='extra info')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('position',
                 models.CharField(blank=True, help_text='Manager, etc', max_length=255, verbose_name='position')),
                ('legal_person', models.BooleanField(default=False, verbose_name='legal person')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True,
                                                                      upload_to=nc_auth.models.user.upload_logo,
                                                                      verbose_name='avatar')),
            ],
            options={
                'verbose_name_plural': 'auth users',
                'verbose_name': 'auth user',
            },
            managers=[
                ('objects', nc_auth.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(default=nc_auth.utils.generate_string, editable=False, max_length=128, primary_key=True, serialize=False, verbose_name='key')),
                ('platform', models.SlugField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android')], default='web', verbose_name='platform')),
                ('version', models.FloatField(default=1.0, verbose_name='version')),
                ('client', models.CharField(default='', max_length=1024, verbose_name='client')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Auth tokens',
                'verbose_name': 'Auth token',
            },
        ),
    ]
