# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 07:47
from __future__ import unicode_literals

import django.db.models.deletion
import positions.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('more_info', models.TextField(blank=True)),
                ('inn', models.BigIntegerField()),
                ('checking_account', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('passport_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('passport_number', models.PositiveIntegerField(blank=True, null=True)),
                ('passport_date', models.DateField(blank=True, null=True)),
                ('passport_given_by', models.CharField(blank=True, max_length=500)),
                ('mail_code', models.IntegerField(blank=True, null=True)),
                ('ip_name', models.CharField(blank=True, max_length=255)),
                ('fact_address', models.CharField(blank=True, max_length=500)),
                ('mail_address', models.CharField(blank=True, max_length=500)),
                ('ogrn', models.CharField(blank=True, max_length=15)),
                ('okpo', models.CharField(blank=True, max_length=15)),
                ('correspondent_account', models.CharField(blank=True, max_length=255)),
                ('bank', models.CharField(blank=True, max_length=255)),
                ('bik', models.CharField(blank=True, max_length=255)),
                ('document', models.CharField(blank=True, max_length=255)),
                ('general_manager', models.CharField(blank=True, max_length=255)),
                ('kpp', models.CharField(blank=True, max_length=15)),
                ('_type_face', models.CharField(choices=[('phys', 'Физ. лицо'), ('ip', 'ИП'), ('ooo', 'ООО'), ('pao', 'ПАО'), ('zao', 'ЗАО'), ('other', 'other')], default='other', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'verbose_name': 'Client',
            },
        ),
        migrations.CreateModel(
            name='ClientExtraTypeFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clients extra types',
                'verbose_name': 'Client extra type',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('position', positions.fields.PositionField(default=-1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc_clients.Client')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'verbose_name': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Groups',
                'verbose_name': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='ffffff', max_length=6)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='_extra_type_face',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nc_clients.ClientExtraTypeFace'),
        ),
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nc_clients.Group'),
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='relations',
            field=models.ManyToManyField(blank=True, related_name='_client_relations_+', to='nc_clients.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nc_clients.Tag'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='user_modified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clientextratypeface',
            unique_together=set([('value', 'user')]),
        ),
    ]
