# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nc_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
