# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nc_clients', '0002_auto_20180221_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bik',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождение'),
        ),
        migrations.AlterField(
            model_name='client',
            name='checking_account',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=25, null=True,
                                      verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='correspondent_account',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=25, null=True,
                                      verbose_name='Корресподентский счет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(blank=True, max_length=255, verbose_name='На основании'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fact_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='general_manager',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ген. директор'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ip_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное название ИП'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Потовый адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ogrn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='okpo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_given_by',
            field=models.CharField(blank=True, max_length=500, verbose_name='Паспорт выдан'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True,
                                      verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_serial',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True,
                                      verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
