# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nc_clients', '0003_auto_20180222_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
