# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='name')),
                ('verbose_name', models.CharField(blank=True, max_length=255, verbose_name='verbose name')),
                ('type', models.CharField(choices=[('global', 'Global module'), ('card', 'Card module')], max_length=20,
                                          verbose_name='type')),
            ],
            options={
                'verbose_name_plural': 'Modules',
                'verbose_name': 'Module',
            },
        ),
    ]
