# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 12:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import nc_notes.models.note


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nc_workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Text')),
                ('audio',
                 models.FileField(blank=True, default='', null=True, upload_to=nc_notes.models.note.Note.get_file_path,
                                  verbose_name='Audio file')),
                ('file',
                 models.FileField(blank=True, default='', null=True, upload_to=nc_notes.models.note.Note.get_file_path,
                                  verbose_name='File')),
                ('image',
                 models.ImageField(blank=True, default='', null=True, upload_to=nc_notes.models.note.Note.get_file_path,
                                   verbose_name='Image file')),
                ('audio_duration', models.PositiveSmallIntegerField(blank=True, default=0, null=True,
                                                                    verbose_name='Audio file duration')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc_workflow.Card',
                                           verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
